### ISSUE TITLE
Use hex value for colors

### ISSUE THREAD

**Issue by ghost** [kazumihanda/test#1]
https://github.com/kazumihanda/test/blob/3eb3a8455e6e8b4f0e45e47a5d479b9242985cb7/app.css#L2

It's better to use the hex value instead of the color name.

red =`#ff0000`
black = `#000`

**Comment by kazumihanda** [comment]
えらいすみません

**Comment by kazumihanda** [comment]
fixed with 4c3ba4468a0ec92c6f939410a02bc19d834ce8a5
